### ISSUE TITLE
Calling activity() instead of activity in Kotlin

### ISSUE THREAD

**Issue by schott12521** [codechimp-org/Android-Studio-Templates#1]
https://github.com/codechimp-org/Android-Studio-Templates/blob/041fc13128ad2f86cec466de8e3c8ba5b189129d/activities/FlatSettingsActivity/root/src/app_package/SettingsActivity.kt.ftl#L102

**Comment by andrew-codechimp** [comment]
I've changed that in the latest commit

**Comment by schott12521** [comment]
I had to change mine from 

`activity().onBackPressed()`

to 

`activity.onBackPressed`

but thanks! Love the template

**Comment by andrew-codechimp** [comment]
You were right `activity.onBackPressed()` is what it should have been, now fixed.
